### ISSUE TITLE
database schema 

### ISSUE THREAD

**Issue by sugarfunk** [amulya/teambuilder#1]
I'm newer to Python and trying to build a program to make small groups. I found your code and it seems to be a very much head start to what I'm trying to make, but your code doesn't create the tables. I assume you are making the table manually? Do you happen to have the ability to export a --no-data database schema ?

**Comment by amulya** [comment]
Hi! I'd be happy to share that with you. I've included the SQL I used to create each table I used in the attachment.
[Dump20200316.zip](https://github.com/amulya/teambuilder/files/4339460/Dump20200316.zip)
